# Generated by Django 5.1.4 on 2025-03-20 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IITPStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.CharField(choices=[('WD', 'Web Development'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('DA', 'Data Analysis'), ('CS', 'Cyber Security')], max_length=2)),
            ],
        ),
    ]
