# Generated by Django 5.1.4 on 2025-03-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iitpstudent',
            name='description',
            field=models.TextField(default='This is a student of IITP'),
        ),
    ]
